project:
  type: book
  output-dir: docs

book:

  title: "Microscopy Core Resources"
  author: "ISMMS Microscopy Core"
  chapters:
    - index.qmd
    - intro.qmd
    - instruments.qmd
    - image-analysis.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    toc: true
    Number-sections: true



